"""Tests for TemplateWriter."""

import pytest
from pathlib import Path

from envdiff.env_template import EnvTemplate, TemplateEntry, TemplateGenerator
from envdiff.template_writer import TemplateWriter


@pytest.fixture
def simple_template() -> EnvTemplate:
    return EnvTemplate(
        entries=[
            TemplateEntry(key="APP_ENV", placeholder="production"),
            TemplateEntry(key="SECRET_KEY", placeholder="CHANGE_ME", comment="sensitive"),
        ]
    )


@pytest.fixture
def writer() -> TemplateWriter:
    return TemplateWriter()


def test_render_includes_header(writer, simple_template):
    rendered = writer.render(simple_template)
    assert "Auto-generated by envdiff" in rendered


def test_render_includes_keys(writer, simple_template):
    rendered = writer.render(simple_template)
    assert "APP_ENV=production" in rendered
    assert "SECRET_KEY=CHANGE_ME" in rendered


def test_render_ends_with_newline(writer, simple_template):
    rendered = writer.render(simple_template)
    assert rendered.endswith("\n")


def test_write_creates_file(tmp_path, simple_template):
    out = tmp_path / ".env.example"
    writer = TemplateWriter(output_path=out)
    result = writer.write(simple_template)
    assert result == out
    assert out.exists()


def test_write_file_content(tmp_path, simple_template):
    out = tmp_path / ".env.example"
    writer = TemplateWriter(output_path=out)
    writer.write(simple_template)
    content = out.read_text()
    assert "APP_ENV" in content


def test_write_creates_parent_dirs(tmp_path, simple_template):
    out = tmp_path / "nested" / "dir" / ".env.example"
    writer = TemplateWriter(output_path=out)
    writer.write(simple_template)
    assert out.exists()


def test_write_without_output_path_raises(writer, simple_template):
    with pytest.raises(ValueError, match="output_path"):
        writer.write(simple_template)


def test_default_filename():
    assert TemplateWriter.default_filename() == ".env.example"
