"""Tests for EnvWriter."""

from pathlib import Path

import pytest

from envdiff.env_writer import EnvWriter


@pytest.fixture
def writer():
    return EnvWriter()


def test_render_simple_keys(writer):
    env = {"HOST": "localhost", "PORT": "5432"}
    result = writer.render(env)
    assert "HOST=localhost" in result
    assert "PORT=5432" in result


def test_render_empty_value(writer):
    env = {"EMPTY": ""}
    result = writer.render(env)
    assert 'EMPTY=""' in result


def test_render_value_with_spaces(writer):
    env = {"GREETING": "hello world"}
    result = writer.render(env)
    assert 'GREETING="hello world"' in result


def test_render_value_with_hash(writer):
    env = {"COLOR": "#FF0000"}
    result = writer.render(env)
    assert 'COLOR="#FF0000"' in result


def test_render_value_with_embedded_quote(writer):
    env = {"MSG": 'say "hi"'}
    result = writer.render(env)
    assert 'MSG="say \\"hi\\""' in result


def test_render_with_header(writer):
    env = {"KEY": "val"}
    result = writer.render(env, header="Generated by envdiff")
    assert result.startswith("# Generated by envdiff")


def test_render_with_export_flag():
    w = EnvWriter(indent_exports=True)
    env = {"API_KEY": "abc123"}
    result = w.render(env)
    assert "export API_KEY=abc123" in result


def test_render_sorted_keys():
    w = EnvWriter(sort_keys=True)
    env = {"ZEBRA": "z", "ALPHA": "a", "MIDDLE": "m"}
    result = w.render(env)
    lines = [l for l in result.splitlines() if l and not l.startswith("#")]
    keys = [l.split("=")[0] for l in lines]
    assert keys == sorted(keys)


def test_write_creates_file(tmp_path):
    w = EnvWriter()
    out = tmp_path / "output" / ".env.merged"
    w.write({"DB": "postgres"}, out)
    assert out.exists()
    content = out.read_text()
    assert "DB=postgres" in content


def test_write_creates_parent_dirs(tmp_path):
    w = EnvWriter()
    nested = tmp_path / "a" / "b" / "c" / ".env"
    w.write({"X": "1"}, nested)
    assert nested.exists()


def test_trailing_newline(writer):
    result = writer.render({"K": "v"})
    assert result.endswith("\n")


def test_default_filename():
    assert EnvWriter.default_filename() == ".env.merged"
