"""Write rendered EnvTemplate to disk."""

from __future__ import annotations

from pathlib import Path
from typing import Optional

from envdiff.env_template import EnvTemplate


class TemplateWriter:
    """Handles writing an EnvTemplate to a file or stdout."""

    def __init__(self, output_path: Optional[Path] = None) -> None:
        self._output_path = output_path

    def render(self, template: EnvTemplate) -> str:
        header = (
            "# Auto-generated by envdiff — do NOT commit real secrets\n"
            "# Fill in values before use\n"
        )
        return header + template.render() + "\n"

    def write(self, template: EnvTemplate) -> Path:
        """Write to file and return the path written."""
        if self._output_path is None:
            raise ValueError("output_path must be set before calling write()")
        content = self.render(template)
        self._ensure_parent(self._output_path)
        self._output_path.write_text(content, encoding="utf-8")
        return self._output_path

    def print(self, template: EnvTemplate) -> None:
        """Print rendered template to stdout."""
        print(self.render(template), end="")

    @staticmethod
    def default_filename() -> str:
        return ".env.example"

    @staticmethod
    def _ensure_parent(path: Path) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
